[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[[redirects]]
  from = "/api/*"
  to = "/api.php"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200