[build]
  publish = "."
  command = "echo 'Static site - no build required'"

# PHP function for API endpoints
[functions]
  directory = "api"

# Redirect API calls to PHP functions
[[redirects]]
  from = "/api/process"
  to = "/api/process.php"
  status = 200
  force = true

# Handle SPA routing - this should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200